priors:
  amp: [-20., -5.]
  tilt: [-5., 5.]
  TM: [0., 6.]
  OMS: [0., 30.]
simulate:
  store_name: data_store
  store_size: 100_000
  chunk_size: 500
train:
  trainer_dir: training_dir
  train_fraction: 0.85
  train_batch_size: 2048
  val_batch_size: 2048
  num_workers: 0
  device: cpu
  n_devices: 1
  min_epochs: 1
  max_epochs: 100
  early_stopping_patience: 100
  learning_rate: 1.e-5
  lr_scheduler:
    type: ReduceLROnPlateua
    lr_scheduler_factor: 0.1
    lr_scheduler_patience: 100
  logger:
    type: wandb
    name: saqqara
    project: saqqara
    entity: wandb-uname
    offline: False
    log_model: all
    save_dir: saqqara-logger